apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector: # choose what to monitor
    matchLabels:
      app: posts
  template: # settings of what we're creating
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: nsp86/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
